version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - "./db:/development.sqlite3"
      - "./db:/test.sqlite3"
    stdin_open: true
    tty: true
    command: bundle exec ruby lib/main.rb
